INSERT INTO NUMBERS_DATASETS (DATASET_CODE) VALUES ('DATASET_1');
INSERT INTO NUMBERS_DATASETS (DATASET_CODE) VALUES ('DATASET_2');
INSERT INTO NUMBERS_DATASETS (DATASET_CODE) VALUES ('DATASET_3');

INSERT INTO DATASETS_VALUES (NUMBERS_DATASETS_ID, NUMBER_VALUE) VALUES (1, 1);
INSERT INTO DATASETS_VALUES (NUMBERS_DATASETS_ID, NUMBER_VALUE) VALUES (1, 15);
INSERT INTO DATASETS_VALUES (NUMBERS_DATASETS_ID, NUMBER_VALUE) VALUES (1, 5);
INSERT INTO DATASETS_VALUES (NUMBERS_DATASETS_ID, NUMBER_VALUE) VALUES (1, 7);
INSERT INTO DATASETS_VALUES (NUMBERS_DATASETS_ID, NUMBER_VALUE) VALUES (1, 3);

INSERT INTO DATASETS_VALUES (NUMBERS_DATASETS_ID, NUMBER_VALUE) VALUES (2, 8);
INSERT INTO DATASETS_VALUES (NUMBERS_DATASETS_ID, NUMBER_VALUE) VALUES (2, 16);
INSERT INTO DATASETS_VALUES (NUMBERS_DATASETS_ID, NUMBER_VALUE) VALUES (2, 31);
INSERT INTO DATASETS_VALUES (NUMBERS_DATASETS_ID, NUMBER_VALUE) VALUES (2, 32);
INSERT INTO DATASETS_VALUES (NUMBERS_DATASETS_ID, NUMBER_VALUE) VALUES (2, 64);
INSERT INTO DATASETS_VALUES (NUMBERS_DATASETS_ID, NUMBER_VALUE) VALUES (2, 128);
INSERT INTO DATASETS_VALUES (NUMBERS_DATASETS_ID, NUMBER_VALUE) VALUES (2, 15);
INSERT INTO DATASETS_VALUES (NUMBERS_DATASETS_ID, NUMBER_VALUE) VALUES (2, 256);

INSERT INTO DATASETS_VALUES (NUMBERS_DATASETS_ID, NUMBER_VALUE) VALUES (3, 0);
INSERT INTO DATASETS_VALUES (NUMBERS_DATASETS_ID, NUMBER_VALUE) VALUES (3, 1);
INSERT INTO DATASETS_VALUES (NUMBERS_DATASETS_ID, NUMBER_VALUE) VALUES (3, 2);
INSERT INTO DATASETS_VALUES (NUMBERS_DATASETS_ID, NUMBER_VALUE) VALUES (3, 3);
INSERT INTO DATASETS_VALUES (NUMBERS_DATASETS_ID, NUMBER_VALUE) VALUES (3, 4);
INSERT INTO DATASETS_VALUES (NUMBERS_DATASETS_ID, NUMBER_VALUE) VALUES (3, 5);
INSERT INTO DATASETS_VALUES (NUMBERS_DATASETS_ID, NUMBER_VALUE) VALUES (3, 6);
INSERT INTO DATASETS_VALUES (NUMBERS_DATASETS_ID, NUMBER_VALUE) VALUES (3, 7);
INSERT INTO DATASETS_VALUES (NUMBERS_DATASETS_ID, NUMBER_VALUE) VALUES (3, 8);
INSERT INTO DATASETS_VALUES (NUMBERS_DATASETS_ID, NUMBER_VALUE) VALUES (3, 9);
INSERT INTO DATASETS_VALUES (NUMBERS_DATASETS_ID, NUMBER_VALUE) VALUES (3, 10);
